// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAutoKillRule(arg1:string,arg2:number,arg3:number,arg4:boolean):Promise<main.AutoKillRule>;

export function CheckAutoKillRules():Promise<Array<main.ProcessInfo>>;

export function CheckForUpdate():Promise<main.UpdateCheckResult>;

export function ConfirmKill(arg1:string,arg2:number):Promise<boolean>;

export function ConfirmKillSelected(arg1:number):Promise<boolean>;

export function FilterProcesses(arg1:number,arg2:number,arg3:boolean):Promise<Array<main.ProcessInfo>>;

export function GetAppVersion():Promise<Record<string, string>>;

export function GetAutoKillRules():Promise<Array<main.AutoKillRule>>;

export function GetProcesses():Promise<Array<main.ProcessInfo>>;

export function GetSystemStats():Promise<main.SystemStats>;

export function KillProcess(arg1:number):Promise<void>;

export function KillProcesses(arg1:Array<number>):Promise<Record<number, string>>;

export function OpenDownloadPage(arg1:string):Promise<void>;

export function RemoveAutoKillRule(arg1:string):Promise<boolean>;

export function SearchProcesses(arg1:string):Promise<Array<main.ProcessInfo>>;

export function TestAutoKillRule(arg1:string,arg2:boolean):Promise<Array<main.ProcessInfo>>;

export function ToggleAutoKillRule(arg1:string,arg2:boolean):Promise<boolean>;

export function UpdateAutoKillRule(arg1:string,arg2:string,arg3:number,arg4:number,arg5:boolean):Promise<boolean>;
