// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAutoKillRule(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddAutoKillRule'](arg1, arg2, arg3, arg4);
}

export function CheckAutoKillRules() {
  return window['go']['main']['App']['CheckAutoKillRules']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ConfirmKill(arg1, arg2) {
  return window['go']['main']['App']['ConfirmKill'](arg1, arg2);
}

export function ConfirmKillSelected(arg1) {
  return window['go']['main']['App']['ConfirmKillSelected'](arg1);
}

export function FilterProcesses(arg1, arg2, arg3) {
  return window['go']['main']['App']['FilterProcesses'](arg1, arg2, arg3);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAutoKillRules() {
  return window['go']['main']['App']['GetAutoKillRules']();
}

export function GetProcesses() {
  return window['go']['main']['App']['GetProcesses']();
}

export function GetSystemStats() {
  return window['go']['main']['App']['GetSystemStats']();
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function KillProcesses(arg1) {
  return window['go']['main']['App']['KillProcesses'](arg1);
}

export function OpenDownloadPage(arg1) {
  return window['go']['main']['App']['OpenDownloadPage'](arg1);
}

export function RemoveAutoKillRule(arg1) {
  return window['go']['main']['App']['RemoveAutoKillRule'](arg1);
}

export function SearchProcesses(arg1) {
  return window['go']['main']['App']['SearchProcesses'](arg1);
}

export function TestAutoKillRule(arg1, arg2) {
  return window['go']['main']['App']['TestAutoKillRule'](arg1, arg2);
}

export function ToggleAutoKillRule(arg1, arg2) {
  return window['go']['main']['App']['ToggleAutoKillRule'](arg1, arg2);
}

export function UpdateAutoKillRule(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateAutoKillRule'](arg1, arg2, arg3, arg4, arg5);
}
